### ISSUE TITLE
Getting Immersive response is not a constructor error while running

### ISSUE THREAD

**Issue by nidhinkumar06** [actions-on-google/dialogflow-interactive-canvas-nodejs#3]
I have used the dialogflow inline editor to write the function but when i run the application i am getting the following error.

```
TypeError: ImmersiveResponse is not a constructor
    at app.intent (/srv/index.js:36:12)
    at Function.<anonymous> (/srv/node_modules/actions-on-google/dist/service/dialogflow/dialogflow.js:152:27)
    at Generator.next (<anonymous>)
    at /srv/node_modules/actions-on-google/dist/service/dialogflow/dialogflow.js:22:71
    at new Promise (<anonymous>)
    at __awaiter (/srv/node_modules/actions-on-google/dist/service/dialogflow/dialogflow.js:18:12)
    at Function.handler (/srv/node_modules/actions-on-google/dist/service/dialogflow/dialogflow.js:85:16)
    at Object.<anonymous> (/srv/node_modules/actions-on-google/dist/assistant.js:55:32)
    at Generator.next (<anonymous>)
    at /srv/node_modules/actions-on-google/dist/assistant.js:22:71
```

Package.json:

```
{
  "name": "dialogflowFirebaseFulfillment",
  "description": "This is the default fulfillment for a Dialogflow agents using Cloud Functions for Firebase",
  "version": "0.0.1",
  "private": true,
  "license": "Apache Version 2.0",
  "author": "Google Inc.",
  "engines": {
    "node": "8"
  },
  "scripts": {
    "start": "firebase serve --only functions:dialogflowFirebaseFulfillment",
    "deploy": "firebase deploy --only functions:dialogflowFirebaseFulfillment"
  },
  "dependencies": {
    "actions-on-google": "^2.7.0-preview.2",
    "firebase-admin": "^5.13.1",
    "firebase-functions": "^2.0.2",
    "dialogflow": "^0.6.0",
    "dialogflow-fulfillment": "^0.5.0"
  }
}
```

Index.js

```
'use strict';

const functions = require('firebase-functions');
const {dialogflow, ImmersiveResponse} = require('actions-on-google');

// map of human speakable colors to color values
const tints = {
  red: 0xFF0000,
  green: 0x00FF00,
  blue: 0x0000FF,
};

const firebaseConfig = JSON.parse(process.env.FIREBASE_CONFIG);

const app = dialogflow({debug: true});

app.intent('welcome', (conv) => {
  conv.ask('Welcome! Do you want me to change color or pause spinning? ' +
    'You can also tell me to ask you later.');
  conv.ask(new ImmersiveResponse({
    url:  //added the hosted url,
  }));
});

app.intent('fallback', (conv) => {
  conv.ask(`I don't understand. You can change my color or pause spinning.`);
  conv.ask(new ImmersiveResponse({
    state: {
      query: conv.query,
    },
  }));
});

app.intent('color', (conv, {color}) => {
  if (color in tints) {
    conv.ask(`Ok, I changed my color to ${color}. What else?`);
    conv.ask(new ImmersiveResponse({
      state: {
        tint: tints[color],
      },
    }));
    return;
  }
  conv.ask(`Sorry, I don't know that color. ` +
    `I only know what red, blue, and green are.`);
  conv.ask(new ImmersiveResponse({
    state: {
      query: conv.query,
    },
  }));
});

app.intent('start', (conv) => {
  conv.ask(`Ok, I'm spinning. What else?`);
  conv.ask(new ImmersiveResponse({
    state: {
      spin: true,
    },
  }));
});

app.intent('pause', (conv) => {
  conv.ask('Ok, I paused spinning. What else?');
  conv.ask(new ImmersiveResponse({
    state: {
      spin: false,
    },
  }));
});

app.intent('timer', (conv) => {
  conv.ask(`Ok, I'll ask you again in 5 seconds`);
  conv.ask(new ImmersiveResponse({
    suppress: true,
    state: {
      timer: 5,
    },
  }));
});

app.intent('instructions', (conv) => {
  conv.ask('Do you want me to change color or pause spinning? ' +
    'You can also tell me to ask you later.');
  conv.ask(new ImmersiveResponse({
    state: {
      instructions: true,
    },
  }));
});

exports.dialogflowFirebaseFulfillment = functions.https.onRequest(app);
```

**Comment by LeonNicholls** [comment]
The package.json dependency for Actions on Google should be:
"actions-on-google": "preview"
